### ISSUE TITLE
Missing manifest.json File and Multiple Dependency Issues

### ISSUE THREAD

**Issue by yugalkaushik** [AOSSIE-Org/Social-Street-Smart#44]
Problem:
Missing manifest.json file:
The repository appears to be missing a crucial manifest.json file for the Chrome extension, which is necessary for defining the extension's configuration and permissions. Without this file, the extension cannot be properly loaded and tested, causing issues in the setup for testing Chrome extension functionality.

Dependency Issues:
The project has several dependency issues, such as mismatched versions or missing dependencies that are causing errors during the setup or execution of the tests.

**Comment by vishavsingla** [comment]
Hey @yugalkaushik manifest.json is present in lib folder of client(old one) and public folder of NewClient folder, run npm i first to run dependencies there aren't any errors.
